[project]
name = "plachtis"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "Django>=6.0.0,<6.1.0",
    "django-solo==2.5.1",
    "gunicorn==21.2.0",
    "python-dotenv==1.0.0",
    "whitenoise==6.6.0",
]